<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <DisableWinExeOutputInference>true</DisableWinExeOutputInference>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\PixelArtAseprite.Tests\Fixtures.cs" Link="AsepriteFixtures.cs" />
    <Using Include="System.Drawing" />
    <Using Include="System.IO" />
    <ProjectReference Include="..\PixelArtAlignment\PixelArtAlignment.csproj" />
    <ProjectReference Include="..\DomainColorTest\DomainColorTest.csproj" />
  </ItemGroup>
</Project>
